channels:
  - conda-forge
dependencies:
  - python=3.10.16
  - pip<=25.1
  - pip:
      - mlflow==2.22.0
      - attrs==25.3.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - matplotlib==3.10.3
      - numpy==2.2.6
      - pydot==4.0.0
      - pytorch-lightning==2.5.1.post0
      - rich==14.0.0
      - scipy==1.15.3
      - torchvision==0.22.0
name: mlflow-env
