name: pytest

on:
  pull_request:
    branches: [master]
  push:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.16"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.2" # или ваша текущая

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Run tests
        run:
          poetry run pytest tests/ \ -m "not requires_files" \
          --cov=lung_cancer_detection \ --cov-report=xml \ -v

      - name: Upload coverage
        uses: codecov/codecov-action@v3

      - name: Notify about skipped model tests
        run: |
          echo "Skipped tests marked with @pytest.mark.requires_files"
          echo "To run them locally: poetry run pytest -m requires_files"
