name: pytest

on:
  pull_request:
    branches: [master]
  push:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.10.16
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.16

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-regressions torch torchvision pytorch-lightning

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests/ \
            -m "not requires_files" \
            --cov=cats_and_dogs \
            --cov-report=xml \
            -v

      - name: Upload coverage
        uses: codecov/codecov-action@v3

      - name: Notify about skipped model tests
        run: |
          echo "Skipped tests marked with @pytest.mark.requires_files"
          echo "To run them locally: pytest -m requires_files"
